# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: The Object Oriented Way
author: Christopher Okhravi & Chat GPT (Illustrations by Midjourney)
#logo: images/logo.png
logo: https://cdn.discordapp.com/attachments/1118630713084870736/1134043079523967067/chrokh_simple_flat_logo_of_bank_vault_purple_pink_blue_purple_m_3ca3faf9-73e1-4b48-b61c-ee3c142e38d3.png
copyright: "All rights reserved"

execute:
  # Force re-execution of notebooks on each build.
  # See https://jupyterbook.org/content/execute.html
  execute_notebooks: force

# To shorten build time, only build files present in TOC.
only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Files to exclude
exclude_patterns: [README.md]

# Information about where the book exists on the web
repository:
  url: https://github.com/chrokh/the-oo-way  # Online location of your book

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  #google_analytics_id: G-V69WNXD095 (Installed manually instead, see below googletagmanager + static analytics.js file)
  use_issues_button: true
  use_repository_button: false
  use_edit_page_button: false

# Sphinx theme and configuration
sphinx:
  config:
    html_js_files: [["https://www.googletagmanager.com/gtag/js?id=G-V69WNXD095", {}]]
    bibtex_reference_style: author_year
    html_theme: furo
  extra_extensions:
    - sphinx_exercise

