name: gh-pages

# Only run this when the main branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Setup python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Install jupyter-book and dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Install dotnet
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    # https://github.com/dotnet/interactive/blob/main/docs/NotebookswithJupyter.md

    # Install dotnet interactive
    - name: Install dotnet try for Jupyter 1/1
      run: dotnet tool install -g Microsoft.dotnet-interactive

    # Install dotnet Jupyter kernel
    - name: Install dotnet Jupyter kernel
      run: dotnet interactive jupyter install

    # Verify that the kernel is available
    - name: Verify that the kernel is available
      run: jupyter kernelspec list

    # Build the book
    - name: Build the book
      run: |
        make html

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        cname: theobjectorientedway.com
